---
- hosts: all

  tasks:
    - include_role:
        name: 2PRecuperatorio
    
    - include_role:
        name: instala-tools_Aranda
          
    - name: "Otra tarea"
      debug:
        msg: "Despues de la ejecucion del rol"

